### ISSUE TITLE
Stimuli presentation

### ISSUE THREAD

**Issue by MarcoViola88** [RealityBending/FictionEro#1]
Last time I checked the exp the stimuli presentation was around 2sec (after 1sec fixation cross & 1sec realistic/artificial cueing).
I discussed with AA and MM and we were wondering whether we should not consider the following:
a) a slightly longer exposition time (e.g. 3-4 secs). While having relatively short timing might be good to avoid extra-long experiment & to prevent people from assessing realness, the current time seems a bit too fast to have our participants getting "horny" and "un-horny"
b) cueing: I am no native, but to me "photo" sounds more real-ish than "picture"
c) cueing not disappearing: are we sure about keeping the cue visible for just 1sec? Why not keeping it visible together with the picture?

**Comment by MarcoViola88** [comment]
In order to balance longer exposition times, we might consider to avoid presenting orientation incongruent stimuli, thus cutting down the number of stimuli seen by each participant to 56 (instead of 80). 
As far as I understood it, the rationale for presenting all the stimuli to everybody was to have stimuli that DO NOT elicit erotic arousal. However, shouldn't the non-erotic pictures play that very role?

**Comment by DominiqueMakowski** [comment]
a)

>  to prevent people from assessing realness

Yes I think that's quite important. We can give it a try with 3 seconds 

b) 

> "photo" sounds more real-ish than "picture"

agreed

c) I don't think it changes much (their attention will be transferred to explore the picture once they read the text anyway), but it feels like it would create some confound to have the overlap, it would be slightly cleaner that the target stimuli (the image) is always the same regardless of the condition (otherwise we have an overlap between the experimental manipulation and the stimulus). We can present it for longer, maybe 1.5 s?

d) 

> we might consider to avoid presenting orientation incongruent stimuli
> the rationale for presenting all the stimuli to everybody was to have stimuli that DO NOT elicit erotic arousal. However, shouldn't the non-erotic pictures play that very role?

I think there is different arguments to be made:

1. Presenting different stimuli lists to different participants depending on some categorical self-reported variables (sex and orientation) is a bit annoying statistically, I'd prefer to have all stimuli viewed by everybody to be able to compute interactions effects properly
2. This makes the strong assumption that pics of males for hetero-males are non-erotic, and pics of female for hetero-females are non-erotic, which I don't think is the case. The validation shows that for females both men and females is arousing, and for males the aversive nature is also "erotic" in nature IMO and phenomenological different from non-erotic negative or positive arousing stims 

I would much prefer to have the whole set, and eventually do a filtering based on sex&orientation a posteriori. But it's interesting to keep them 1) to properly explore the space of effects (otherwise you removing some interesting parts of the "range" of effects, especially for men) and 2) you lose robustness as you have less stims in the same "space" (especially for females where there's an overlap)
 
e. What do you think of adding some sort of "How convincing is the image" scale?

**Comment by MarcoViola88** [comment]
a) let's try 3 secs then! (although maybe some of us should do some 1st-person testing right before launching data collection in order to fine-tune these micro-details)

c) you convinced me, I drop the previous objection. Let's go with 1.5 sec (and then we can manipulate that in the test maybe?)

d) I am happy to defer to the statitsticians for the statistics. But then, if we keep the entire set, we might try to ask a question about sexyness that nudges people to rate as SEXY even those pictures that are incongruent with their sexual tastes, hence lowly AROUSING?

**Comment by DominiqueMakowski** [comment]
a) I'll make the changes to the task and let you know once it's done, but yes in case we will need to run some pilots on ourselves to refine these details hehe
d) good idea. We  need to be think about the phrasing

**Comment by guidocor** [comment]
Regarding point b) what about instead photo or picture... just "Image"?

**Comment by DominiqueMakowski** [comment]
I'm closing this one as it the main discussion is on #2
