### ISSUE TITLE
Data Analysis

### ISSUE THREAD

**Issue by DominiqueMakowski** [RealityBending/FictionEro#15]
I'd like to group the samples into bigger categories, such as: 

- Incentivized students (via credits / money)
- Non-incentivized students 
- General population (through social media etc.)
- Other useful major category?

Could you guys help me confirm which of the current samples are of which category are the samples below?

![image](https://github.com/RealityBending/FictionEro/assets/8875533/b813d1af-9862-4b62-b27d-8f53a01e940a)

**Comment by MarcoViola88** [comment]
Hi Dominique,
here are the categories I know:

- enter = non-incentivized students
- gacon = general pop
- macre = non-incentivized students
- mafas = general pop
- marmar = general pop
- mavio = general pop
- piaca = non-incentivized students
- sobon = general pop
- unime = non-incentivized students

**Comment by hadisbabakhani** [comment]
classroom: Non-incentivized students
enter: General population (could be through social media, depending on the recruitment method)
gacon: General population (if not specified otherwise, might be a platform or tool)
macre: Incentivized students (assuming it involves credits/money)
mafas: General population (unless specified otherwise)
marmar: General population
mavio: General population
Other: Other
piaca: General population
Reddit: General population (through social media)
RISC: General population (or specific research participant pool, could be "Other" if specified as such)
Snowball: General population (method where participants recruit other participants)
sobon: General population (if not specified otherwise)
SONA: Incentivized students (typically a platform for student recruitment involving credits)
Student: Non-incentivized students
unime: General population (if not specified otherwise)
Grouped Categories:
Incentivized students (via credits / money):
macre
SONA
Non-incentivized students:
classroom
Student
General population (through social media etc.):
enter
gacon
mafas
marmar
mavio
piaca
Reddit
RISC
Snowball
sobon
unime

**Comment by MarcoViola88** [comment]
Hello Hadisbabakhani, nice to meet you -- you're @DominiqueMakowski student/collaborator, I guess?

Please note that "enter", "macre", "unime" refer to student population (NOT incentivized).

Whereas "gacon", "mafas", "mavio", "piaca", "sobon" refer to general population.

**Comment by DominiqueMakowski** [comment]
Not at all actually... (@AnafNeves is the one you're thinking of ;)

@hadisbabakhani are you related to the project?
