### ISSUE TITLE
FictionEro - Analysis

### ISSUE THREAD

**Issue by DominiqueMakowski** [RealityBending/FictionEro#16]
- [ ] Add textual details in the analysis

**Comment by DominiqueMakowski** [comment]
(testing the GitHub roadmap feature - don't mind this)

**Comment by DominiqueMakowski** [comment]
Hi all, we're pretty much done with the analysis.

Should we schedule a meeting before we go on summer breaks so that we can walk you through and discuss the next steps? @MarcoViola88 feel free to send us a doodle :)

**Comment by MarcoViola88** [comment]
Hi guys,
here's a Doodle:  [https://doodle.com/meeting/participate/id/dGQOg63a](https://doodle.com/meeting/participate/id/dGQOg63a)
(Sending it via email too)

I picked European afternoon in order to allow Antonio to participate in the morning.
I skipped dates when I'm not available.

@DominiqueMakowski what plan do you propose? Just presenting & discussing results? Or also sketching Study 2?

**Comment by DominiqueMakowski** [comment]
Following discussion, consider:

- Subsamples: add an anova for age of samples
- Do a corrected condition for the believed results (i.e., re-categorize "condition" based on realness scale)
- Test also effect of realness as a moderator of emotion
- Check effect of nationality 
- Inter-rater reliability:  Investigate whether there was a high consensus for the realness scale 
  - Compute ICC
  - Compute SNR 
  - Make plot of distribution per item
