### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by MarcoViola88** [RealityBending/FictionEro#3]
![image](https://github.com/RealityBending/FictionEro/assets/150437296/757d89fc-c0c3-434e-9680-49b56bc1e523)

Please answer the following questions = Per favore rispondi alle seguenti domande
What is your biological sex?* = Qual è il tuo sesso biologico?

Male = Maschio
Female = Femmina
Other = Altro

What is your highest completed education level?* = Qual il tuo titolo di studio più avanzato che hai conseguito?

University (doctorate) = Università (dottorato)
University (master) or equivalent = Università (laurea magistrale) o equivalente
University (bachelor) or equivalent  = Università (laurea triennale) o equivalente
High school or equivalent  = Diploma di maturità o equivalente
Primary school = Scuole primarie
Other = Altro

Continue = Continua

**Comment by MarcoViola88** [comment]
![image](https://github.com/RealityBending/FictionEro/assets/150437296/1955d4ae-4ed4-40c4-a26e-d8055981f418)

Please enter your age (in years) = Per favore immetti la tuà età (anni)

e.g., '31' = es. '31'
Please enter your ethnicity = Per favore immetti la tua etnia

e.g., Caucasian = es. Caucasica
In which country do you currently live? = In che paese vivi attualmente?

e.g., UK, Spain = es. Italia, Regno Unito [NB not a literal translation obviously]

Continue = Continua

**Comment by MarcoViola88** [comment]
![image](https://github.com/RealityBending/FictionEro/assets/150437296/b76293fb-ce5a-421d-b2ec-544cec376f95)

How would you rate your level of English? = Come descriveresti la tua padronanza dell'Italiano?
Beginner ... Fluent = Principiante ... Fluente

How knowledgeable do you consider yourself about Artificial Intelligence (AI) technology? = Quanto sei familiare con le tecnologie di l'Intelligenza Artificiale?
Not at all ... Expert = Per niente ... Esperta/o

Continue = Continua

**Comment by MarcoViola88** [comment]
![image](https://github.com/RealityBending/FictionEro/assets/150437296/95a99de9-9350-4b37-ac67-38a2ef614190)
Not 100% sure how to modify this one, so @DominiqueMakowski could you jump in here too please?

**Comment by DominiqueMakowski** [comment]
Thanks Marco M


> What's the minimum target number of participants?

Maybe check the [discussion](https://github.com/RealityBending/FictionEro/discussions) thread where I provide some info (also check the one about the multiverse analysis and let me know what you think 😉 ). I think that 100 would be a minimum

> How should we recruit these participants?

Yes, sample heterogeneity is a fair point, and currently we're doing it pretty randomly here (i.e., disseminating wherever convenient), which has its issues (especially, the reddit samples are 100% guys and fairly tech/AI-savy). I'm not sure how easily we can align these collection approaches though... But I think this relates to the next point

> Will we have the possibility to track the progress of data collection? 

Yes we can! Thanks to the recent addition of "URL" variables (`?exp=something` at the end of the URL), we can add "trackers" to identify the source. For instance, here's the current history of dissemination (from [this cleaning script](https://realitybending.github.io/FictionEro/analysis/1_cleaning.html)):

![image](https://github.com/RealityBending/FictionEro/assets/8875533/fe9d9bad-2558-41f5-8464-9229b66e26ec)

Each "reddit" is a separate post, "Experimenter1" is the dissertation student (this is because I need to separately keep track of how many they collect), "snow" is snowball (participants that sent the link that shows at the end of the experiment) and "website" is the rebel website. Basically you can write anything in the `exp` url variable and it will get tracked. 

So we will know which participants are from prolific, which are from reddit, which are from other sources etc., which means we can then compare them and investigate potential differences (tbf in general I think I prefer to have more data from a variety of sources rather than less data from a very specific collection source - It's not a lab experiment anyway so we might as well as go full diverse as long as we track who comes from where).

> final link for participants?

Link will be: https://realitybending.github.io/FictionEro/experiment/italian?exp=readme&lang=it
But as said you'll need to adjust the url variable `exp` to track the source. Note that `lang` must be `=it` so that we can easily discriminate the language

 > contraceptive use in women

This was added because one of our neuroscience student wants to control for the role of hormonal admixture and its role in arousal modulation. On the one hand, I'd say let's keep it, since it's been ethically cleared & it's explicitly marked as non-required anyway, and this way we have the same data for everybody (we didn't have any issues with this question here, but then it's true that England is likely more liberal than italy), but if really you feel like that's problematic feel free to consider removing it for the italian version (it would require creating a separate `questionnaire.js` file). But I think we might be slightly overcautious (which is not a bad thing per se don't get me wrong haha), I mean we get people to watch erotic images and ask how aroused they are, so I don't think this question is particularly more off-throwing

> The way we ask about sexual orientation 

Same as above, I think it's fine... (+ this one is quite important for analysis I'd say)


> participants' English proficiency

Yes this one you are supposed to change it to the relevant language (@marcosperduti also to *french*). Agreed since the italian sample is going to be mostly native italians it's less important but... I'd say, if the sample is likely to contain (international) students, let's keep it just in case (also this way I don't have to create various questionnaire versions). It's not like it adds a lot of time...


> On every screen displaying the scores for a stimulus, the button to continue is in English

I'll check that. You mean the scales screen? Could you let me know if there are other instances of not translated things?

**Comment by MarcoViola88** [comment]
RE: the contraceptive question

- Would it be problematic to move it at the end of the questionnaire? I might be overly cautious indeed, but since a lot of my colleagues were scared about sharing a link with sexual images with their students (sigh), I am afraid that might scare even more participants away...
- In any case, I noticed a potential (little) issue in the questions: the option "No" might encompass BOTH males (No, I'm not a female) AND females that use no contraceptive. Do you think that'll be a issue?


RE: data collection
I'm asking a favor to some colleagues, i.e. to share the link with their students. 
Currently I'm circulating the following links: 

- https://realitybending.github.io/FictionEro/experiment/italian?exp=sobon&lang=it -- sobon stands for "Sofia Bonicalzi" -- maybe we should acknowledge her.

- https://realitybending.github.io/FictionEro/experiment/italian?exp=enter&lang=it -- for "Enrico Terrone". But he'll see his students only in March!

- https://realitybending.github.io/FictionEro/experiment/italian?exp=mafas&lang=it -- for "Marco Fasoli", though he's still not sure he'll spread it vastly

**Comment by MarcoViola88** [comment]
- ... bu let me try with Reddit too ...e.g. here https://realitybending.github.io/FictionEro/experiment/italian?exp=reddita1&lang=it  and beyond (@DominiqueMakowski if you can share your 'pick-up lines' I'd be happy to take some inspiration!)

**Comment by DominiqueMakowski** [comment]
(wait before spreading it until I fix the buttons translation and enable data saving), let me share the 2 successful posts

**Comment by DominiqueMakowski** [comment]
- https://www.reddit.com/r/aiArt/comments/1aduhkx/is_aigenerated_erotic_art_going_to_replace_real/
- https://www.reddit.com/r/Futurology/comments/19emsca/how_do_you_react_to_aigenerated_erotic_content_a/

> In any case, I noticed a potential (little) issue in the questions

The contraception option only shows up for women normally... unless I hardcoded the english response, I'll double check and fix it if need be

**Comment by marcosperduti** [comment]
> Yes this one you are supposed to change it to the relevant language (@marcosperduti also to _french_).

Yes, I've changed it :) 

> * if you can share your 'pick-up lines' I'd be happy to take some inspiration!)

Me too!

**Comment by marcosperduti** [comment]
> contraceptive use in women

Hi all, I've some problem with this question...I understand the its aim, but beyond the questions itself, what I found little bit displaced is that we ask for contraceptive use ONLY for woman, and ironically "partner's contraceptive" is one possible answer!
It wouldn't be better to generally ask for contraceptive use, with the list of possible contraceptive (probably adding options that male participants can choose -condoms)? 
@DominiqueMakowski if you're then interested only in women responses, you can just skip males' ones.

**Comment by MarcoViola88** [comment]
> * There's also a question investigating the participants' English proficiency. Personally, I'd remove it, but if we want an additional control, I'd replace "Inglese" with "Italiano."

I noticed I didn't modify that until now -- apology!
That means that if someone completed the EXP in Italian before now (i.e., before February 2nd, 2024, 16:30 Italian Time), he/she/they might have answered the question with respect to English, rather than with respect to Italian.
Honestly I suspect that won't do much difference (also because I suspect there are max 3, maybe 0 subjects that completed the ITA experiment!) -- but I'm putting this here just to keep track.

I'm also finding some more colleagues who are available to share the link with their students -- though some of them will begin their teaching in (mid-)March, and hopefully we might have concluded data collection by then ... ?

**Comment by DominiqueMakowski** [comment]
> That means that if someone completed the EXP in Italian before now 

Wait Marco but data collection for italian version is not enabled yet! did you start collecting already??

**Comment by MarcoViola88** [comment]
Well, I started sharing some links with some colleagues who might send it to students; and made a couple of posts on Reddit.
So, yes, I kind of begun sharing it -- though very 'softly'.
Can I help fixing the remaining issues? (button, questions)

**Comment by DominiqueMakowski** [comment]
Ah sorry for the miscommunication, can you withhold while we finalize everything, I'll try to fix the button now but can you tell me which screen is it exactly?

**Comment by DominiqueMakowski** [comment]
Fixed the button on the scales

⚠️ ⚠️ data collection is now enabled for the italian version (make sure to test with e.g., `exp=test` so that we don't mix real data from us)

let's gooo 🤞  (let me know once you suspect that one participant has participated so that I can adjust the script and make sure it got saved correctly)

**Comment by MarcoViola88** [comment]
> Ah sorry for the miscommunication, can you withhold while we finalize everything, I'll try to fix the button now but can you tell me which screen is it exactly?

My fault, I probably got overwhelmed by the enthusiasm, sorry for rushing you XD
And yeah, I'll share the link in the following days (though the group-sharing will probably begin only in a couple of weeks)

**Comment by DominiqueMakowski** [comment]
PS: I checked and everything works we get the data correctly :)
